# PATH: runtime/claude_executor.py

import json
import os
from typing import Dict, Any


class ClaudeExecutionError(RuntimeError):
    pass


def run_claude(task: Dict[str, Any]) -> Dict[str, Any]:
    """
    LOW-LEVEL EXECUTION STUB

    This function represents the ONLY place where
    Claude Code integration is allowed.

    For now:
    - no real execution
    - no API calls
    - deterministic stub output

    This will later be replaced by a real Claude adapter.
    """
    raise NotImplementedError("Claude execution backend not wired yet.")


class ClaudeExecutor:
    """
    Executes a Claude Code build based strictly on a
    SAPIANTA_BUILD_PLAN_V1 JSON artifact.

    Responsibilities:
    - load and verify build plan
    - pass plan to Claude execution backend
    - persist raw Claude output

    This class:
    - does NOT modify the build plan
    - does NOT perform validation
    - does NOT make governance decisions
    """

    EXPECTED_PROTOCOL = "SAPIANTA_BUILD_PLAN_V1"

    def __init__(self, build_plan_path: str, output_root: str):
        self.build_plan_path = build_plan_path
        self.output_root = output_root

    def execute(self) -> None:
        build_plan = self._load_build_plan()
        self._prepare_output_root()

        # ---- EXECUTION BOUNDARY ----
        raw_output = self._execute_with_backend(build_plan)

        self._write_raw_output(raw_output)

        print("[CLAUDE] Execution completed")

    # ---------- internals ----------

    def _load_build_plan(self) -> Dict[str, Any]:
        if not os.path.exists(self.build_plan_path):
            raise ClaudeExecutionError(
                f"Build plan not found: {self.build_plan_path}"
            )

        with open(self.build_plan_path, "r", encoding="utf-8") as f:
            data = json.load(f)

        if data.get("protocol") != self.EXPECTED_PROTOCOL:
            raise ClaudeExecutionError(
                f"Invalid build plan protocol: {data.get('protocol')}"
            )

        return data

    def _prepare_output_root(self) -> None:
        os.makedirs(self.output_root, exist_ok=True)

    def _execute_with_backend(self, build_plan: Dict[str, Any]) -> Dict[str, Any]:
        """
        Delegates execution to the Claude backend.

        Currently falls back to a deterministic stub
        until a real Claude adapter is connected.
        """
        try:
            return run_claude(build_plan)
        except NotImplementedError:
            # ✅ DETERMINISTIC STUB OUTPUT (TEST ONLY)
            return {
                "files": {
                    "modules/test_module/__init__.py": "",
                    "modules/test_module/core.py": (
                        "# test module generated by Claude stub\n"
                        "def hello():\n"
                        "    return 'hello from test module'\n"
                    ),
                }
            }

    def _write_raw_output(self, output: Dict[str, Any]) -> None:
        out_path = os.path.join(self.output_root, "claude_raw_output.json")

        with open(out_path, "w", encoding="utf-8") as f:
            json.dump(output, f, indent=2, ensure_ascii=False)

        print(f"[CLAUDE] Raw output written to {out_path}")
