"""
SAPIANTA Code Generator v0.7

CRITICAL FIX:
- Creates separate pytest-compatible test files
- Enables proper test discovery
"""

import os
from pathlib import Path

from runtime.development.mutation_validator import MutationValidator
from runtime.development.generated_code_sanitizer import GeneratedCodeSanitizer
from runtime.development.module_test_runner import ModuleTestRunner


PROJECT_ROOT = Path(__file__).resolve().parents[2]


class CodeGenerator:

    def __init__(self):

        self.project_root = PROJECT_ROOT
        self.validator = MutationValidator()
        self.sanitizer = GeneratedCodeSanitizer()
        self.tester = ModuleTestRunner()

        # 🔥 FAILURE INJECTION FLAG
        self.force_failure = True

    # ------------------------------------------------

    def generate_module(self, file_path: str, description: str):

        full_path = self.project_root / file_path

        if full_path.exists():
            print(f"[CODEGEN] File already exists: {file_path}")
            return

        os.makedirs(full_path.parent, exist_ok=True)

        template = self._generate_template(file_path, description)
        template = self.sanitizer.sanitize(template)

        # ------------------------------------------------
        # CREATE MODULE FILE
        # ------------------------------------------------

        with open(full_path, "w") as f:
            f.write(template)

        print(f"[CODEGEN] Module created: {file_path}")

        # ------------------------------------------------
        # 🔥 CREATE TEST FILE (CRITICAL FIX)
        # ------------------------------------------------

        class_name = self._infer_class_name(file_path)

        test_file_name = f"test_{full_path.stem}.py"
        test_file_path = full_path.parent / test_file_name

        test_code = f'''
from {full_path.stem} import {class_name}


def test_basic():
    instance = {class_name}()
    result = instance.run({{}})
    assert result is not None
'''

        with open(test_file_path, "w") as f:
            f.write(test_code)

        print(f"[CODEGEN] Test file created: {test_file_path}")

        # ------------------------------------------------
        # MODULE TEST
        # ------------------------------------------------

        test_result = self.tester.test_module(file_path)

        print("[CODEGEN] Module test result:", test_result)

        if test_result["status"] != "PASSED":
            print("[CODEGEN] Test failed — keeping module for auto-fix")
            return

        # ------------------------------------------------
        # MUTATION VALIDATION
        # ------------------------------------------------

        validation = self.validator.validate_changes([file_path])

        print("[CODEGEN] Mutation validation result:")

        for r in validation:
            print(r)

    # ------------------------------------------------

    def _generate_template(self, file_path: str, description: str):

        class_name = self._infer_class_name(file_path)

        if self.force_failure:
            return f'''"""
{class_name}

{description}

Auto-generated by SAPIANTA (FAILURE MODE)
"""

class {class_name}:

    def __init__(self):
        pass

    def run(self, context):
        return foo()  # intentional failure
'''

        return f'''"""
{class_name}

{description}

Auto-generated by SAPIANTA
"""

class {class_name}:

    def __init__(self):
        pass

    def run(self, context):
        raise NotImplementedError("{class_name} not implemented")
'''

    # ------------------------------------------------

    def _infer_class_name(self, file_path: str):

        name = Path(file_path).stem
        parts = name.split("_")

        return "".join(p.capitalize() for p in parts)