"""
SAPIANTA Code Generator v0.3

Responsible for generating new runtime modules based on
approved architecture proposals.

Pipeline

architecture proposal
↓
template generation
↓
code sanitization
↓
file creation
↓
module test
↓
mutation validation
"""

import os
from pathlib import Path

from runtime.development.mutation_validator import MutationValidator
from runtime.development.generated_code_sanitizer import GeneratedCodeSanitizer
from runtime.development.module_test_runner import ModuleTestRunner


PROJECT_ROOT = Path(__file__).resolve().parents[2]


class CodeGenerator:

    def __init__(self):

        self.project_root = PROJECT_ROOT
        self.validator = MutationValidator()
        self.sanitizer = GeneratedCodeSanitizer()
        self.tester = ModuleTestRunner()

    # ------------------------------------------------

    def generate_module(self, file_path: str, description: str):
        """
        Generate a new python module based on proposal.
        """

        full_path = self.project_root / file_path

        if full_path.exists():
            print(f"[CODEGEN] File already exists: {file_path}")
            return

        os.makedirs(full_path.parent, exist_ok=True)

        template = self._generate_template(file_path, description)

        # sanitize generated code
        template = self.sanitizer.sanitize(template)

        # write module file
        with open(full_path, "w") as f:
            f.write(template)

        print(f"[CODEGEN] Module created: {file_path}")

        # ------------------------------------------------
        # MODULE TEST
        # ------------------------------------------------

        test_result = self.tester.test_module(file_path)

        print("[CODEGEN] Module test result:", test_result)

        if test_result["status"] != "PASSED":

            print("[CODEGEN] Test failed — removing module")

            os.remove(full_path)

            return

        # ------------------------------------------------
        # MUTATION VALIDATION
        # ------------------------------------------------

        validation = self.validator.validate_changes([file_path])

        print("[CODEGEN] Mutation validation result:")

        for r in validation:
            print(r)

    # ------------------------------------------------

    def _generate_template(self, file_path: str, description: str):

        class_name = self._infer_class_name(file_path)

        return f'''"""
{class_name}

{description}

Auto-generated by SAPIANTA
"""

class {class_name}:

    def __init__(self):
        pass

    def run(self, context):
        """
        Main execution entry.
        """
        raise NotImplementedError(
            "{class_name} logic not implemented yet"
        )
'''

    # ------------------------------------------------

    def _infer_class_name(self, file_path: str):

        name = Path(file_path).stem

        parts = name.split("_")

        class_name = "".join(p.capitalize() for p in parts)

        return class_name