"""
SAPIANTA Development Task Planner

Provides prioritization and scheduling of development tasks.

Purpose:
Determine execution order for tasks generated by
sapianta discuss and development runtime.
"""


class DevTaskPlanner:
    """
    Basic development task planning engine.
    """

    def __init__(self):
        pass

    def score_task(self, task: dict) -> int:
        """
        Assign a priority score to a task.
        Higher score = higher priority.
        """

        score = 0

        task_type = task.get("task_type", "")
        idea = task.get("idea", "").lower()

        if task_type == "bugfix":
            score += 100

        if task_type == "test":
            score += 80

        if "security" in idea:
            score += 70

        if "performance" in idea:
            score += 50

        if task_type == "implementation":
            score += 30

        return score

    def prioritize(self, tasks: list) -> list:
        """
        Sort tasks by priority.
        """

        return sorted(
            tasks,
            key=lambda t: self.score_task(t),
            reverse=True
        )