"""
SAPIANTA Development Task Hash

Provides deterministic hashing for development tasks.

Purpose:
Detect duplicate tasks generated by AI systems such as
sapianta discuss or autonomous development modules.
"""

import hashlib
import json


def normalize_task(task: dict) -> dict:
    """
    Normalize task structure for deterministic hashing.
    """

    normalized = {
        "task_type": task.get("task_type", ""),
        "idea": task.get("idea", "").strip().lower(),
        "source": task.get("source", ""),
    }

    return normalized


def compute_task_hash(task: dict) -> str:
    """
    Compute deterministic SHA256 hash of a development task.
    """

    normalized = normalize_task(task)

    encoded = json.dumps(normalized, sort_keys=True)

    return hashlib.sha256(encoded.encode()).hexdigest()


def is_duplicate(task: dict, existing_hashes: set) -> bool:
    """
    Check if task is already present in registry.
    """

    task_hash = compute_task_hash(task)

    return task_hash in existing_hashes