"""
SAPIANTA Development Task Registry

Tracks development tasks generated by:

- sapianta discuss
- dev orchestrator
- future autonomous development agents

Purpose:
Provide deterministic tracking of the development backlog.

This implementation uses persistent JSON storage so that tasks
survive across CLI processes.
"""

import json
import os
import hashlib
from typing import List, Dict


REGISTRY_FILE = os.path.join(
    os.path.dirname(__file__),
    "task_registry.json"
)

# 🔥 Explicit task states
TASK_STATES = {
    "queued",
    "running",
    "waiting_approval",
    "approved",
    "completed",
    "failed",
    "blocked"
}


class DevTaskRegistry:
    """
    Registry for development tasks with persistent storage.
    """

    def __init__(self, reset: bool = False):

        self._ensure_file()

        if reset:
            data = {
                "active_tasks": [],
                "completed_tasks": [],
                "rejected_tasks": []
            }

            with open(REGISTRY_FILE, "w") as f:
                json.dump(data, f, indent=2)

        with open(REGISTRY_FILE, "r") as f:
            data = json.load(f)

        self.active_tasks: List[Dict] = data.get("active_tasks", [])
        self.completed_tasks: List[Dict] = data.get("completed_tasks", [])
        self.rejected_tasks: List[Dict] = data.get("rejected_tasks", [])

    def _ensure_file(self):

        if not os.path.exists(REGISTRY_FILE):

            data = {
                "active_tasks": [],
                "completed_tasks": [],
                "rejected_tasks": []
            }

            with open(REGISTRY_FILE, "w") as f:
                json.dump(data, f, indent=2)

    def _persist(self):

        data = {
            "active_tasks": self.active_tasks,
            "completed_tasks": self.completed_tasks,
            "rejected_tasks": self.rejected_tasks
        }

        with open(REGISTRY_FILE, "w") as f:
            json.dump(data, f, indent=2)

    # 🔑 deterministic ID
    def _generate_task_id(self, task: Dict) -> str:
        base = f"{task.get('goal','')}|{task.get('priority',0)}"
        return hashlib.sha256(base.encode()).hexdigest()

    def _ensure_state(self, task: Dict) -> None:
        state = task.get("state")

        if state not in TASK_STATES:
            task["state"] = "queued"

    def add_task(self, task: Dict) -> None:

        task_id = self._generate_task_id(task)

        # dedup
        for existing in self.active_tasks:
            existing_id = existing.get("id") or self._generate_task_id(existing)
            if existing_id == task_id:
                return

        task["id"] = task_id
        self._ensure_state(task)

        self.active_tasks.append(task)
        self._persist()

    def update_task_state(self, task: Dict, new_state: str) -> None:
        """
        Update task state deterministically.
        """

        if new_state not in TASK_STATES:
            return

        task_id = task.get("id")

        for t in self.active_tasks:
            if t.get("id") == task_id:
                t["state"] = new_state
                task["state"] = new_state  # sync reference
                break

        self._persist()

    def complete_task(self, task: Dict) -> None:
        """
        Move task to completed (terminal state).
        """

        task_id = task.get("id")

        self.active_tasks = [
            t for t in self.active_tasks
            if t.get("id") != task_id
        ]

        task["state"] = "completed"

        if task not in self.completed_tasks:
            self.completed_tasks.append(task)

        self._persist()

    def reject_task(self, task: Dict) -> None:
        """
        Move task to failed (terminal state).
        """

        task_id = task.get("id")

        self.active_tasks = [
            t for t in self.active_tasks
            if t.get("id") != task_id
        ]

        task["state"] = "failed"

        if task not in self.rejected_tasks:
            self.rejected_tasks.append(task)

        self._persist()

    def get_active_tasks(self) -> List[Dict]:
        return list(self.active_tasks)

    def get_completed_tasks(self) -> List[Dict]:
        return list(self.completed_tasks)

    def get_rejected_tasks(self) -> List[Dict]:
        return list(self.rejected_tasks)

    # 🔥 FIXED QUERY LAYER
    def get_tasks_by_state(self, state: str) -> List[Dict]:

        if state == "completed":
            return [
                t for t in self.completed_tasks
                if t.get("state") == state
            ]

        if state == "failed":
            return [
                t for t in self.rejected_tasks
                if t.get("state") == state
            ]

        return [
            t for t in self.active_tasks
            if t.get("state") == state
        ]