"""
SAPIANTA Development Task Hash

Provides deterministic hashing for development tasks.

Purpose:
Detect duplicate tasks generated by AI systems such as
sapianta discuss or autonomous development modules.
"""

import hashlib
import json


def normalize_task(task: dict) -> dict:
    """
    Normalize task structure for deterministic hashing.
    Supports current SAPIANTA schema (goal + priority).
    Backward compatible with legacy fields (idea).
    """

    goal = task.get("goal") or task.get("idea", "")

    return {
        "goal": goal.strip().lower() if isinstance(goal, str) else "",
        "priority": task.get("priority", 0)
    }


def compute_task_hash(task: dict) -> str:
    """
    Compute deterministic SHA256 hash of a development task.
    """

    normalized = normalize_task(task)

    encoded = json.dumps(normalized, sort_keys=True, separators=(",", ":"))

    return hashlib.sha256(encoded.encode("utf-8")).hexdigest()


def is_duplicate(task: dict, existing_hashes: set) -> bool:
    """
    Check if task is already present in registry.
    """

    task_hash = compute_task_hash(task)

    return task_hash in existing_hashes