"""
SAPIANTA Development Task Planner

Provides prioritization and scheduling of development tasks.

Purpose:
Determine execution order for tasks generated by
sapianta discuss and development runtime.
"""


class DevTaskPlanner:
    """
    Basic development task planning engine.
    """

    def __init__(self):
        pass

    def score_task(self, task: dict) -> int:
        """
        Assign a priority score to a task.
        Higher score = higher priority.
        """

        score = 0

        task_type = task.get("task_type", "")
        idea = task.get("idea", "").lower()

        if task_type == "bugfix":
            score += 100

        if task_type == "test":
            score += 80

        if "security" in idea:
            score += 70

        if "performance" in idea:
            score += 50

        if task_type == "implementation":
            score += 30

        return score

    def prioritize(self, tasks: list) -> list:
        """
        Sort tasks by priority.
        """

        # Preserve deterministic behavior:
        # - stable sort
        # - combine heuristic + metadata score

        def _score(task):
            metadata = task.get("metadata", {})

            # Cold-start bias correction:
            # new tasks (no score) get small positive default to ensure exploration
            metadata_score = metadata.get("score", 0.1)

            heuristic_score = self.score_task(task)

            return metadata_score + heuristic_score

        return sorted(
            tasks,
            key=_score,
            reverse=True
        )