"""
SAPIANTA Development Task Registry

Tracks development tasks generated by:

- sapianta discuss
- dev orchestrator
- future autonomous development agents

Purpose:
Provide deterministic tracking of the development backlog.

This implementation uses persistent JSON storage so that tasks
survive across CLI processes.
"""

import json
import os
import hashlib
from typing import List, Dict


REGISTRY_FILE = os.path.join(
    os.path.dirname(__file__),
    "task_registry.json"
)


class DevTaskRegistry:
    """
    Registry for development tasks with persistent storage.
    """

    def __init__(self, reset: bool = False):

        self._ensure_file()

        # deterministic reset mode for tests
        if reset:
            data = {
                "active_tasks": [],
                "completed_tasks": [],
                "rejected_tasks": []
            }

            with open(REGISTRY_FILE, "w") as f:
                json.dump(data, f, indent=2)

        with open(REGISTRY_FILE, "r") as f:
            data = json.load(f)

        self.active_tasks: List[Dict] = data.get("active_tasks", [])
        self.completed_tasks: List[Dict] = data.get("completed_tasks", [])
        self.rejected_tasks: List[Dict] = data.get("rejected_tasks", [])

    def _ensure_file(self):

        if not os.path.exists(REGISTRY_FILE):

            data = {
                "active_tasks": [],
                "completed_tasks": [],
                "rejected_tasks": []
            }

            with open(REGISTRY_FILE, "w") as f:
                json.dump(data, f, indent=2)

    def _persist(self):

        data = {
            "active_tasks": self.active_tasks,
            "completed_tasks": self.completed_tasks,
            "rejected_tasks": self.rejected_tasks
        }

        with open(REGISTRY_FILE, "w") as f:
            json.dump(data, f, indent=2)

    # 🔑 determinističen ID
    def _generate_task_id(self, task: Dict) -> str:
        """
        Generate deterministic task ID based on content.
        """
        base = f"{task.get('goal','')}|{task.get('priority',0)}"
        return hashlib.sha256(base.encode()).hexdigest()

    def add_task(self, task: Dict) -> None:
        """
        Register a new development task (with deduplication).
        """

        task_id = self._generate_task_id(task)

        # dedup check (works for both new + legacy tasks)
        for existing in self.active_tasks:
            existing_id = existing.get("id") or self._generate_task_id(existing)
            if existing_id == task_id:
                return

        # assign ID
        task["id"] = task_id

        self.active_tasks.append(task)
        self._persist()

    def complete_task(self, task: Dict) -> None:
        """
        Mark task as completed and remove it from active queue.
        """

        task_id = task.get("id")

        # remove by ID (robust)
        self.active_tasks = [
            t for t in self.active_tasks
            if t.get("id") != task_id
        ]

        # prevent duplicates
        if task not in self.completed_tasks:
            self.completed_tasks.append(task)

        self._persist()

    def reject_task(self, task: Dict) -> None:
        """
        Mark task as rejected.
        """

        task_id = task.get("id")

        self.active_tasks = [
            t for t in self.active_tasks
            if t.get("id") != task_id
        ]

        if task not in self.rejected_tasks:
            self.rejected_tasks.append(task)

        self._persist()

    def get_active_tasks(self) -> List[Dict]:
        return list(self.active_tasks)

    def get_completed_tasks(self) -> List[Dict]:
        return list(self.completed_tasks)

    def get_rejected_tasks(self) -> List[Dict]:
        return list(self.rejected_tasks)