"""
SAPIANTA Development Task Registry

Tracks development tasks generated by:

- sapianta discuss
- dev orchestrator
- future autonomous development agents

Purpose:
Provide deterministic tracking of the development backlog.

This implementation uses persistent JSON storage so that tasks
survive across CLI processes.
"""

import json
import os
from typing import List, Dict


REGISTRY_FILE = os.path.join(
    os.path.dirname(__file__),
    "task_registry.json"
)


class DevTaskRegistry:
    """
    Registry for development tasks with persistent storage.
    """

    def __init__(self):

        self._ensure_file()

        with open(REGISTRY_FILE, "r") as f:
            data = json.load(f)

        self.active_tasks: List[Dict] = data.get("active_tasks", [])
        self.completed_tasks: List[Dict] = data.get("completed_tasks", [])
        self.rejected_tasks: List[Dict] = data.get("rejected_tasks", [])

    def _ensure_file(self):

        if not os.path.exists(REGISTRY_FILE):

            data = {
                "active_tasks": [],
                "completed_tasks": [],
                "rejected_tasks": []
            }

            with open(REGISTRY_FILE, "w") as f:
                json.dump(data, f, indent=2)

    def _persist(self):

        data = {
            "active_tasks": self.active_tasks,
            "completed_tasks": self.completed_tasks,
            "rejected_tasks": self.rejected_tasks
        }

        with open(REGISTRY_FILE, "w") as f:
            json.dump(data, f, indent=2)

    def add_task(self, task: Dict) -> None:
        """
        Register a new development task.
        """
        self.active_tasks.append(task)
        self._persist()

    def complete_task(self, task: Dict) -> None:
        """
        Mark task as completed.
        """
        if task in self.active_tasks:
            self.active_tasks.remove(task)
            self.completed_tasks.append(task)
            self._persist()

    def reject_task(self, task: Dict) -> None:
        """
        Mark task as rejected.
        """
        if task in self.active_tasks:
            self.active_tasks.remove(task)
            self.rejected_tasks.append(task)
            self._persist()

    def get_active_tasks(self) -> List[Dict]:
        return list(self.active_tasks)

    def get_completed_tasks(self) -> List[Dict]:
        return list(self.completed_tasks)

    def get_rejected_tasks(self) -> List[Dict]:
        return list(self.rejected_tasks)