"""
SAPIANTA Development Task Schema

Defines the canonical structure of development tasks generated by:

- sapianta discuss
- dev_orchestrator
- future autonomous development modules

Purpose:
Ensure that development actions are structured and governance-verifiable.
"""

from dataclasses import dataclass
from typing import List, Optional


@dataclass
class DevTask:
    """
    Canonical development task definition.
    """

    task_type: str
    idea: str

    source: str = "unknown"

    # optional governance metadata
    target_module: Optional[str] = None
    expected_tests: Optional[List[str]] = None

    risk_level: str = "low"
    governance_scope: str = "development"


def validate_task(task: dict) -> bool:
    """
    Minimal schema validation.
    """

    required_fields = [
        "task_type",
        "idea",
        "source",
    ]

    for field in required_fields:
        if field not in task:
            raise ValueError(f"Missing required task field: {field}")

    return True