"""
SAPIANTA Generated Code Sanitizer

Purpose
-------
Cleans auto-generated modules before they are accepted
into the runtime system.

Responsibilities
----------------
- remove repo context dumps
- remove LLM instructions
- normalize templates
- ensure minimal deterministic module structure
"""

import re


class GeneratedCodeSanitizer:

    def sanitize(self, code: str) -> str:
        """
        Clean generated code before writing to disk.
        """

        code = self._remove_repo_dump(code)
        code = self._remove_generator_markers(code)

        return code.strip() + "\n"

    # ------------------------------------------------

    def _remove_repo_dump(self, code: str) -> str:
        """
        Remove huge repository context sections.
        """

        pattern = r"SYSTEM CONTEXT.*?Generated by SAPIANTA Code Generator"
        return re.sub(pattern, "", code, flags=re.DOTALL)

    # ------------------------------------------------

    def _remove_generator_markers(self, code: str) -> str:

        lines = code.splitlines()

        cleaned = []

        for line in lines:

            if "Generated by SAPIANTA Code Generator" in line:
                continue

            if "SYSTEM CONTEXT" in line:
                continue

            cleaned.append(line)

        return "\n".join(cleaned)


if __name__ == "__main__":

    sanitizer = GeneratedCodeSanitizer()

    sample = """
    SYSTEM CONTEXT
    runtime/file1.py
    runtime/file2.py
    Generated by SAPIANTA Code Generator
    """

    print(sanitizer.sanitize(sample))